"""add_club_slug

Revision ID: 4d3ab7f09542
Revises: add_user_hide_from_elo
Create Date: 2026-03-12 14:40:34.981511

"""
from alembic import op
import sqlalchemy as sa
import re


def _slugify(text):
    if not text:
        return ''
    text = re.sub(r'[^\w\s-]', '', text)
    text = text.strip().replace(' ', '_')
    text = re.sub(r'_+', '_', text)
    return text


# revision identifiers, used by Alembic.
revision = '4d3ab7f09542'
down_revision = 'add_user_hide_from_elo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cl_slug', sa.String(length=150), nullable=True))

    # Populate slugs for existing clubs BEFORE adding unique index
    conn = op.get_bind()
    clubs = conn.execute(sa.text("SELECT cl_id, cl_name FROM tb_club")).fetchall()
    existing_slugs = set()
    for cl_id, cl_name in clubs:
        base = _slugify(cl_name)
        slug = base
        counter = 2
        while slug in existing_slugs:
            slug = f"{base}_{counter}"
            counter += 1
        existing_slugs.add(slug)
        conn.execute(
            sa.text("UPDATE tb_club SET cl_slug = :slug WHERE cl_id = :id"),
            {"slug": slug, "id": cl_id}
        )

    with op.batch_alter_table('tb_club', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_club_cl_slug'), ['cl_slug'], unique=True)

    with op.batch_alter_table('tb_event', schema=None) as batch_op:
        batch_op.alter_column('ev_club_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tb_game', schema=None) as batch_op:
        batch_op.alter_column('gm_idLeague',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gm_idGameDay',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gm_teamA',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('gm_teamB',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_game', schema=None) as batch_op:
        batch_op.alter_column('gm_teamB',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('gm_teamA',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('gm_idGameDay',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gm_idLeague',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tb_event', schema=None) as batch_op:
        batch_op.alter_column('ev_club_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tb_club', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_club_cl_slug'))
        batch_op.drop_column('cl_slug')

    # ### end Alembic commands ###
