"""Add event system tables

Revision ID: 5ec9ac2964d2
Revises: b18ac89c6dd2
Create Date: 2025-11-26 20:56:30.173465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec9ac2964d2'
down_revision = 'b18ac89c6dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tb_users')
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.alter_column('us_telephone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint('uq_users_telephone', ['us_telephone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_telephone', type_='unique')
        batch_op.alter_column('us_telephone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.create_table('_alembic_tmp_tb_users',
    sa.Column('us_id', sa.INTEGER(), nullable=False),
    sa.Column('us_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('us_email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('us_pwd', sa.VARCHAR(length=150), nullable=True),
    sa.Column('us_birthday', sa.DATE(), nullable=True),
    sa.Column('us_is_player', sa.BOOLEAN(), nullable=True),
    sa.Column('us_is_manager', sa.BOOLEAN(), nullable=True),
    sa.Column('us_is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('us_is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('us_is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('us_telephone', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('us_id'),
    sa.UniqueConstraint('us_telephone', name=op.f('uq_users_telephone'))
    )
    # ### end Alembic commands ###
