"""add league max players and league players table

Revision ID: a302b73c5609
Revises: add_registration_dates
Create Date: 2025-03-18 17:29:44.692006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a302b73c5609'
down_revision = 'add_registration_dates'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tb_ELO_ranking')
    with op.batch_alter_table('tb_ELO_ranking', schema=None) as batch_op:
        batch_op.drop_column('pl_name')

    with op.batch_alter_table('tb_gameday', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_gameday_winner2', 'tb_users', ['gd_idWinner2'], ['us_id'])
        batch_op.create_foreign_key('fk_gameday_winner1', 'tb_users', ['gd_idWinner1'], ['us_id'])
        batch_op.drop_column('gd_nameWinner2')
        batch_op.drop_column('gd_nameWinner1')

    with op.batch_alter_table('tb_league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lg_max_players', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_league', schema=None) as batch_op:
        batch_op.drop_column('lg_max_players')

    with op.batch_alter_table('tb_gameday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gd_nameWinner1', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('gd_nameWinner2', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_gameday_winner1', type_='foreignkey')
        batch_op.drop_constraint('fk_gameday_winner2', type_='foreignkey')

    with op.batch_alter_table('tb_ELO_ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pl_name', sa.VARCHAR(length=50), nullable=False))

    op.create_table('_alembic_tmp_tb_ELO_ranking',
    sa.Column('pl_id', sa.INTEGER(), nullable=False),
    sa.Column('pl_rankingNow', sa.FLOAT(), nullable=True),
    sa.Column('pl_totalRankingOpo', sa.FLOAT(), nullable=True),
    sa.Column('pl_wins', sa.INTEGER(), nullable=False),
    sa.Column('pl_losses', sa.INTEGER(), nullable=False),
    sa.Column('pl_totalGames', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pl_id'], ['tb_users.us_id'], ),
    sa.PrimaryKeyConstraint('pl_id')
    )
    # ### end Alembic commands ###
