"""add registration dates to league table

Revision ID: add_registration_dates
Revises: 5055aa442094
Create Date: 2024-03-17

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_registration_dates'
down_revision = '5055aa442094'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lg_registration_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('lg_registration_end', sa.DateTime(timezone=True), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_league', schema=None) as batch_op:
        batch_op.drop_column('lg_registration_end')
        batch_op.drop_column('lg_registration_start')