"""Add substitutes and presence points to league

Revision ID: add_league_substitutes
Revises: a302b73c5609
Create Date: 2024-02-14 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_league_substitutes'
down_revision = 'a302b73c5609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lg_nbr_substitutes', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('lg_nbr_auto_substitutes', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('lg_presence_points', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_league', schema=None) as batch_op:
        batch_op.drop_column('lg_presence_points')
        batch_op.drop_column('lg_nbr_auto_substitutes')
        batch_op.drop_column('lg_nbr_substitutes')

    # ### end Alembic commands ###